Spec on_delete: :nullify required behaviour
The `on_delete: :nullify` behaviour is required because
rotating secrets could require deleting an authorized application
such as Civil Apply, without deleting its submission records. The
records may be required for auditing purposes.

Currently deleting an existing authorized application is not possible
as it errors as in the example below:

> old_apply_app = Doorkeeper::Application.find_by(name: "My application")
> old_apply_app.destroy
=>
```sh
PG::ForeignKeyViolation: ERROR:  update or delete on table "oauth_applications" violates foreign key constraint "fk_rails_53889ba261" on table "submissions" (ActiveRecord::InvalidForeignKey)
DETAIL:  Key (id)=(<REDACTED>) is still referenced from table "submissions".
ERROR:  update or delete on table "oauth_applications" violates foreign key constraint "fk_rails_53889ba261" on table "submissions" (PG::ForeignKeyViolation)
DETAIL:  Key (id)=(<REDACTED>) is still referenced from table "submissions".
```